osx_image: xcode7.3
language: objective-c

before_install: 
 - sudo gem install cocoapods -v '1.0'
 - cd Example && rm -rf Pods && pod install && cd -

script:
- xcodebuild -workspace Example/URBNAlert.xcworkspace -scheme URBNAlert-Example clean build -destination "platform=iOS Simulator,name=iPhone 6,OS=latest" -destination-timeout 120 test
- pod lib lint --quick
